<?php require_once './templates/layout/header.phtml' ?>

 <form action='siniestroAdd' method='POST'>
    <h1>Agregar Siniestro</h1>
    <div>
        <label for='asegurado' class='labelAdd'>Nombre Asegurado</label>
        <input type='text' name='asegurado' class='inputAdd' required>
        <label for='typeSiniestro' class='labelAdd'>Tipo de Siniestro</label>
        <input type='text' name='typeSiniestro' class='inputAdd' required>
        <label for='date' class='labelAdd'>Fecha</label>
        <input type='date' name='date' class='inputAdd' required>
    </div>

    <label for='id_aseguradora' class=''>
                Aseguradora:
            </label>
            <select name='id_aseguradora' class='' required>
                <?php foreach($siniestroAseguradoras as $key => $siniestroAseguradora): ?>
                    <option  value='<?php echo $siniestroAseguradora->ID_Aseguradora?>'><?php echo $siniestroAseguradora->Nombre?></option>
            <?php endforeach ?>
        </select>

    <button type='submit'>Guadar</button>
</form>

<?php require_once './templates/layout/footer.phtml' ?>