<?php require_once './templates/layout/header.phtml' ?>
<div class='background-addAseguradora'>
    <form action='aseguradoraAdd' method='POST'>
        <div class='form-addAseguradora'>
            <h1>Agregar Aseguradora</h1>
            <label for='name' class='labelAdd'>Nombre Aseguradora</label>
            <input type='text' name='name' class='inputAdd' required>
            <label for='adress' class='labelAdd'>Dirección</label>
            <input type='text' name='adress' class='inputAdd' required>
            <label for='email' class='labelAdd'>Email</label>
            <input type='email' name='email'  class='inputAdd' required>
            <button type='submit' class='btnGuardar'>Guadar</button>
        </div>
    </form>
    <div class = btn-back>
        <button class='back'><a href="aseguradoras">Atrás</a</button>
    </div>
</div>



<?php require_once './templates/layout/footer.phtml' ?>
