<?php require_once './templates/layout/header.phtml'?>
<?php if (!empty($error)): ?>
    <div class="" role="alert">
        <?= htmlspecialchars($error) ?>
    </div>
<?php endif; ?>
    <form action='login' method='POST' >
        <div class=''>
            <label for='email' class=''  name='email' >Usuario</label>
            <input type='text' class='' name='email' id='email' required>
            <label for='password' class='' name='password' >Contraseña
            <input type='password' class='' name='password' id='password' required>
        </div>
        <button type='submit' class=''>login</button>
    </form>
    
<?php require_once './templates/layout/footer.phtml'?>
