<?php require_once './templates/layout/header.phtml'?>
<?php if (!empty($error)): ?>
    <div class="error" role="alert">
        <?= htmlspecialchars($error) ?>
    </div>
<?php endif; ?>
<div class='background-login'>
    <form action='login' method='POST' >
        <div class='form-login'>
            <h1>Iniciar Sesión</h1>
            <p class='p-login'>Ingreseg Usuario y Contraseña para continuar</p>
            <label for='email' class='formLoginLabel' id='email' name='email' >Usuario</label>
            <input type='text' class='input-formLogin' name='email' id='email' placeholder="Introduce tu usuario" required>
            <label for='password' class='formLoginLabel' id='password' name='password' >Contraseña</label>
            <input type='password' class='input-formLogin' name='password' id='password'placeholder="Introduce tu contraseña"  required>
            <button type='submit'  class='btnLogin'>Login</button>
        </div>
    </form>
</div>
    
<?php require_once './templates/layout/footer.phtml'?>