
<head>
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="./style/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peritajes App</title>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <a class="nav-link" href="/web2/peritajeApp/showlogin">Login</a>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
     
      <?php if ($this->user): ?>
        <li class="nav-item">
          <a class="nav-link" href="href="<?= BASE_URL ?>."/logout"></a>
        </li>
      <?php else: ?>
        <li class="nav-item">
          <a class="nav-link" href="">Logout</a>
        </li>
      <?php endif; ?>
    </ul>
  </div>


    
