<?php
$isLoggedIn = isset($_SESSION['ID_USER']); // Verifica si el usuario está logueado
?>
<head>
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="./style/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peritajes App</title>
</head>
<body>
    <nav>
        <button id="btnToggle" class="menuToggle" >
            <img src="images/menutoggle.png" alt="Menu Hamburguesa">
        </button>
        <ul class="menu" id="menu">
            <li><a href="home">INICIO</a></li>
            <li><a href="aseguradoras">ASEGURADORAS</a></li>
            <li><a href="siniestros">SINIESTROS</a></li>
            <?php if ($isLoggedIn): ?>
                <li><a id="logoutButton" href="<?php echo BASE_URL; ?>logout">LOGOUT</a></li>
            <?php else: ?>
                <li><a id="loginButton" href="<?php echo BASE_URL; ?>showlogin">LOGIN</a></li>
            <?php endif; ?>
        </ul>
    </nav>
</body>














